/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingEventsRouteImport } from './routes/upcoming-events'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReimbursablesRouteImport } from './routes/reimbursables'
import { Route as RawDataRouteImport } from './routes/raw-data'
import { Route as PendingPaymentsRouteImport } from './routes/pending-payments'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as FixedDepositsRouteImport } from './routes/fixed-deposits'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DaybookRouteImport } from './routes/daybook'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as PortalIdRouteImport } from './routes/portal/$id'

const UpcomingEventsRoute = UpcomingEventsRouteImport.update({
  id: '/upcoming-events',
  path: '/upcoming-events',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReimbursablesRoute = ReimbursablesRouteImport.update({
  id: '/reimbursables',
  path: '/reimbursables',
  getParentRoute: () => rootRouteImport,
} as any)
const RawDataRoute = RawDataRouteImport.update({
  id: '/raw-data',
  path: '/raw-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingPaymentsRoute = PendingPaymentsRouteImport.update({
  id: '/pending-payments',
  path: '/pending-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedDepositsRoute = FixedDepositsRouteImport.update({
  id: '/fixed-deposits',
  path: '/fixed-deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DaybookRoute = DaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIdRoute = PortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/daybook': typeof DaybookRoute
  '/delivery': typeof DeliveryRoute
  '/expenses': typeof ExpensesRoute
  '/fixed-deposits': typeof FixedDepositsRoute
  '/payments': typeof PaymentsRoute
  '/pending-payments': typeof PendingPaymentsRoute
  '/raw-data': typeof RawDataRoute
  '/reimbursables': typeof ReimbursablesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/travel': typeof TravelRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/portal/$id': typeof PortalIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/daybook': typeof DaybookRoute
  '/delivery': typeof DeliveryRoute
  '/expenses': typeof ExpensesRoute
  '/fixed-deposits': typeof FixedDepositsRoute
  '/payments': typeof PaymentsRoute
  '/pending-payments': typeof PendingPaymentsRoute
  '/raw-data': typeof RawDataRoute
  '/reimbursables': typeof ReimbursablesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/travel': typeof TravelRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/portal/$id': typeof PortalIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/daybook': typeof DaybookRoute
  '/delivery': typeof DeliveryRoute
  '/expenses': typeof ExpensesRoute
  '/fixed-deposits': typeof FixedDepositsRoute
  '/payments': typeof PaymentsRoute
  '/pending-payments': typeof PendingPaymentsRoute
  '/raw-data': typeof RawDataRoute
  '/reimbursables': typeof ReimbursablesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/tasks': typeof TasksRoute
  '/travel': typeof TravelRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/portal/$id': typeof PortalIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/auth'
    | '/calendar'
    | '/clients'
    | '/daybook'
    | '/delivery'
    | '/expenses'
    | '/fixed-deposits'
    | '/payments'
    | '/pending-payments'
    | '/raw-data'
    | '/reimbursables'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/travel'
    | '/upcoming-events'
    | '/portal/$id'
    | '/projects/$id'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/calendar'
    | '/clients'
    | '/daybook'
    | '/delivery'
    | '/expenses'
    | '/fixed-deposits'
    | '/payments'
    | '/pending-payments'
    | '/raw-data'
    | '/reimbursables'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/travel'
    | '/upcoming-events'
    | '/portal/$id'
    | '/projects/$id'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/auth'
    | '/calendar'
    | '/clients'
    | '/daybook'
    | '/delivery'
    | '/expenses'
    | '/fixed-deposits'
    | '/payments'
    | '/pending-payments'
    | '/raw-data'
    | '/reimbursables'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/travel'
    | '/upcoming-events'
    | '/portal/$id'
    | '/projects/$id'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  DaybookRoute: typeof DaybookRoute
  DeliveryRoute: typeof DeliveryRoute
  ExpensesRoute: typeof ExpensesRoute
  FixedDepositsRoute: typeof FixedDepositsRoute
  PaymentsRoute: typeof PaymentsRoute
  PendingPaymentsRoute: typeof PendingPaymentsRoute
  RawDataRoute: typeof RawDataRoute
  ReimbursablesRoute: typeof ReimbursablesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  TasksRoute: typeof TasksRoute
  TravelRoute: typeof TravelRoute
  UpcomingEventsRoute: typeof UpcomingEventsRoute
  PortalIdRoute: typeof PortalIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming-events': {
      id: '/upcoming-events'
      path: '/upcoming-events'
      fullPath: '/upcoming-events'
      preLoaderRoute: typeof UpcomingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursables': {
      id: '/reimbursables'
      path: '/reimbursables'
      fullPath: '/reimbursables'
      preLoaderRoute: typeof ReimbursablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-data': {
      id: '/raw-data'
      path: '/raw-data'
      fullPath: '/raw-data'
      preLoaderRoute: typeof RawDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-payments': {
      id: '/pending-payments'
      path: '/pending-payments'
      fullPath: '/pending-payments'
      preLoaderRoute: typeof PendingPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-deposits': {
      id: '/fixed-deposits'
      path: '/fixed-deposits'
      fullPath: '/fixed-deposits'
      preLoaderRoute: typeof FixedDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daybook': {
      id: '/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof DaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$id': {
      id: '/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof PortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  DaybookRoute: DaybookRoute,
  DeliveryRoute: DeliveryRoute,
  ExpensesRoute: ExpensesRoute,
  FixedDepositsRoute: FixedDepositsRoute,
  PaymentsRoute: PaymentsRoute,
  PendingPaymentsRoute: PendingPaymentsRoute,
  RawDataRoute: RawDataRoute,
  ReimbursablesRoute: ReimbursablesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  TasksRoute: TasksRoute,
  TravelRoute: TravelRoute,
  UpcomingEventsRoute: UpcomingEventsRoute,
  PortalIdRoute: PortalIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
